language: java
jdk:
  - oraclejdk8
sudo: true
before_install: 
  - chmod +x gradlew 
script: ./gradlew clean build --refresh-dependencies
addons:
  sonarcloud:
    organization: "tasima-dudoguinho"
    token:
      secure: 89bf008ccf33a14e416a76ff3da2952aa63a67ce
script:  
  - sonar-scanner